cd C:\Skrivbord\CCD Ultra Rewrite\CocaineCrackDown\Nez\DefaultContentSource\effects
mgfxc Bevels.fx Bevels.mgfxo /Profile:OpenGL
mgfxc BloomCombine.fx BloomCombine.mgfxo /Profile:OpenGL
mgfxc BloomExtract.fx BloomExtract.mgfxo /Profile:OpenGL
mgfxc Crosshatch.fx Crosshatch.mgfxo /Profile:OpenGL
mgfxc DeferredLighting.fx DeferredLighting.mgfxo /Profile:OpenGL
mgfxc DeferredSprite.fx DeferredSprite.mgfxo /Profile:OpenGL
mgfxc Dissolve.fx Dissolve.mgfxo /Profile:OpenGL
mgfxc ForwardLighting.fx ForwardLighting.mgfxo /Profile:OpenGL
mgfxc GaussianBlur.fx GaussianBlur.mgfxo /Profile:OpenGL
mgfxc Grayscale.fx Grayscale.mgfxo /Profile:OpenGL
mgfxc HeatDistortion.fx HeatDistortion.mgfxo /Profile:OpenGL
mgfxc Invert.fx Invert.mgfxo /Profile:OpenGL
mgfxc Letterbox.fx Letterbox.mgfxo /Profile:OpenGL
mgfxc MultiTexture.fx MultiTexture.mgfxo /Profile:OpenGL
mgfxc MultiTextureOverlay.fx MultiTextureOverlay.mgfxo /Profile:OpenGL
mgfxc Noise.fx Noise.mgfxo /Profile:OpenGL
mgfxc PaletteCycler.fx PaletteCycler.mgfxo /Profile:OpenGL
mgfxc PixelGlitch.fx PixelGlitch.mgfxo /Profile:OpenGL
mgfxc PolygonLight.fx PolygonLight.mgfxo /Profile:OpenGL
mgfxc Reflection.fx Reflection.mgfxo /Profile:OpenGL
mgfxc Scanlines.fx Scanlines.mgfxo /Profile:OpenGL
mgfxc Sepia.fx Sepia.mgfxo /Profile:OpenGL
mgfxc SpriteAlphaTest.fx SpriteAlphaTest.mgfxo /Profile:OpenGL
mgfxc SpriteBlinkEffect.fx SpriteBlinkEffect.mgfxo /Profile:OpenGL
mgfxc SpriteEffect.fx SpriteEffect.mgfxo /Profile:OpenGL
mgfxc SpriteLightMultiply.fx SpriteLightMultiply.mgfxo /Profile:OpenGL
mgfxc SpriteLines.fx SpriteLines.mgfxo /Profile:OpenGL
mgfxc StencilLight.fx StencilLight.mgfxo /Profile:OpenGL
mgfxc Twist.fx Twist.mgfxo /Profile:OpenGL
mgfxc Vignette.fx Vignette.mgfxo /Profile:OpenGL

